### ISSUE TITLE
Systemize given APK: App exists !

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/terminal_app_systemizer#19]
Trying to push an app directly without installation (`3. Systemize given apk`) throws the error `App exists!`, but I haven't installed it before.

**Comment by towith** [comment]
I got problem exactly same

**Comment by towith** [comment]
seems this is caused by missing `awk` and other unix tools on my android system, it's ok after i insatall `busybox`

**Comment by tonyxforce** [comment]
This is happening for me even after i install busybox
